version: '3.8'

services:
  myapp:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8882:8882"
  mongodb:
    image: docker.io/bitnami/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

volumes:
  mongodb_data:
    driver: local